bind = "0.0.0.0:5000"
workers = 1
worker_class = "sync"
worker_connections = 1000
timeout = 7200  # 2 hours to accommodate long processing runs with multiple anti-spam pauses
keepalive = 2
max_requests = 1000
max_requests_jitter = 50
preload_app = True
reload = True